const fs = require('fs');
const assert = require('assert');
const patch = fs.readFileSync('admin_today_history_patch.js', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
assert.match(patch, /const scopes = \{ orders: 'today'/, 'ต้องเปิดหน้าออร์เดอร์ด้วยงานวันนี้');
assert.match(patch, /\['today','งานวันนี้'\]/, 'ต้องมีตัวกรองงานวันนี้');
assert.match(patch, /\['backlog','งานค้าง'\]/, 'ต้องมีตัวกรองงานค้าง');
assert.match(patch, /\['history','ประวัติ'\]/, 'ต้องมีตัวกรองประวัติ');
assert.match(patch, /actionable\(order\) && orderDate\(order\) === today/, 'งานวันนี้ต้องไม่รวมออร์เดอร์ที่ปิดแล้ว');
assert.match(patch, /scope === 'history' \? completed\(order\)/, 'ประวัติต้องเข้าถึงออร์เดอร์ที่ปิดแล้วทุกวัน');
assert.match(patch, /#statOrders/, "ต้องปรับภาพรวมเป็นงานวันนี้");
assert.match(patch, /admin-overview-total/, "ต้องคงยอดสะสมไว้เป็นข้อมูลอ้างอิง");
assert.match(patch, /#cashLedgerTable/, 'ต้องแยกบัญชีเงินสดวันนี้กับประวัติ');
assert.match(patch, /#settlementList tbody/, 'ต้องแยกรอบจ่ายปัจจุบันกับประวัติ');
assert.match(patch, /#withdrawalRequestList tbody/, 'ต้องแยกคำร้องถอนเงินปัจจุบันกับประวัติ');
assert.match(patch, /#creatorCommissionRows/, 'ต้องแยกคิวคอมมิชชันกับประวัติ');
assert.match(patch, /payment_slip_reviews\?select=/, 'ต้องรองรับประวัติการตรวจสลิป');
assert.match(patch, /status=in\.\(approved,needs_reupload\)/, 'ประวัติสลิปต้องดึงเฉพาะรายการที่ตรวจแล้ว');
assert.match(patch, /admin-history-empty/, 'ต้องมีข้อความเมื่อไม่มีข้อมูลในมุมมอง');
assert.match(patch, /hasSourceEmpty/, 'ต้องไม่แสดงข้อความว่างซ้ำเมื่อไม่มีข้อมูลต้นทาง');
assert.match(html, /admin_today_history_patch\.js\?v=admin-today-history-v3/, 'ต้องโหลดแพตช์หลังบ้านใหม่');
console.log('admin today/history contract: PASS');
