const fs = require('fs');
const assert = require('assert');

const admin = fs.readFileSync('admin/admin-app.js', 'utf8');
const accounts = fs.readFileSync('admin/accounts.html', 'utf8');
const profile = fs.readFileSync('admin/profile.html', 'utf8');
const styles = fs.readFileSync('admin/admin-accounts.css', 'utf8');
const compactScript = fs.readFileSync('admin/admin-user-compact-ui.js', 'utf8');

assert.match(admin, /accounts:\s*\(\)\s*=>\s*operationsV2\('admins'\)/, 'accounts.html ต้อง dispatch เข้า Account Control Plane แทน login fallback');
assert.match(admin, /async function operationsV2\(defaultFeature = 'rider-applications'\)/, 'Account Control Plane ต้องรับ default feature สำหรับ route Accounts');
assert.match(admin, /\['admin','Admin'\],\['customer','ลูกค้า'\],\['store_owner','ร้านค้า'\],\['rider','Rider'\]/, 'ต้องมีเมนูรองแยก Admin, ลูกค้า, ร้านค้า และ Rider');
assert.match(admin, /action: 'list_user_control_plane'/, 'Account Management ต้องอ่านข้อมูลจริงจาก central control plane');
assert.match(admin, /action: 'create_managed_account'/, 'ต้องสร้างบัญชี Admin/Customer ผ่าน central access function');
assert.match(admin, /action: 'update_user_profile_section'/, 'ต้องแก้ข้อมูลบัญชีผ่าน Edge Function กลางและบันทึกเฉพาะหมวดข้อมูล');
assert.match(admin, /action: 'set_user_roles'/, 'ต้องแก้ role ผ่าน central access function');
assert.match(admin, /action: 'set_account_control'/, 'ต้องจัดการสถานะ/สิทธิ์ผ่าน central access function');
assert.match(admin, /action: 'adjust_customer_wallet'/, 'การปรับยอด wallet ต้องผ่าน audit-capable central access function');
assert.match(admin, /admin_action_audit\?select=action,reason,actor_id,created_at/, 'รายละเอียดบัญชีต้องโหลด audit history ของบัญชีนั้นจากข้อมูลจริง');
assert.match(admin, /สร้างเมื่อ/, 'รายละเอียดบัญชีต้องแสดงวันสร้างจากข้อมูลจริง');
assert.match(admin, /data-account-action="roles"/, 'รายละเอียดบัญชีต้องมีทางลัดเปลี่ยนบทบาท');
assert.match(admin, /data-account-action="controls"/, 'รายละเอียดบัญชีต้องมีทางลัดเปลี่ยนสถานะและสิทธิ์');
assert.match(admin, /href="stores\.html"/, 'บัญชีร้านค้าต้องเชื่อมไปยัง Store Control Plane');
assert.match(admin, /href="riders\.html"/, 'บัญชี Rider ต้องเชื่อมไปยัง Rider Control Plane');
assert.match(accounts, /data-page="accounts"/, 'Accounts route ต้องคงเป็น MPA route เดิม');
assert.match(accounts, /admin-accounts\.css\?v=accounts-v2/, 'Accounts route ต้อง cache-bust style รายละเอียดบัญชีใหม่');
assert.match(accounts, /admin-app\.js\?v=admin-management-v9/, 'Accounts route ต้อง cache-bust runtime และ governance ล่าสุด');
assert.match(accounts, /admin-override-governance\.js\?v=admin-override-v1/, 'Accounts route ต้องคง governance จากงานร่วม');
assert.match(accounts, /admin-user-compact-ui\.js\?v=user-compact-v2/, 'Accounts route ต้องโหลด action sheet เวอร์ชันที่เก็บคำสั่งเดิมไว้');
assert.match(profile, /data-page="accounts"/, 'profile route เดิมต้องเปิด Account Control Plane แทนหน้า 404');
assert.match(profile, /admin-accounts\.css\?v=accounts-v2/, 'profile route ต้องโหลด style รายละเอียดบัญชีใหม่');
assert.match(profile, /admin-app\.js\?v=admin-management-v9/, 'profile route ต้องโหลด runtime เวอร์ชันเดียวกับ Accounts');
assert.match(profile, /admin-override-governance\.js\?v=admin-override-v1/, 'profile route ต้องคง governance จากงานร่วม');
assert.match(compactScript, /admin-user-compact-actions/, 'เมนูย่อบัญชีต้องเก็บปุ่มคำสั่งเดิมไว้เพื่อเปิด action sheet ได้');
assert.match(styles, /\.admin-account-type-menu/, 'ต้องมี responsive style ของเมนูประเภทบัญชี');
assert.match(styles, /\.admin-account-detail-list/, 'ต้องมีสไตล์รายการรายละเอียดบัญชี');
assert.match(styles, /\.mpa-modal \.mpa-table-wrap/, 'audit table ต้องเลื่อนแนวนอนได้ใน modal');
assert.match(styles, /@media\(max-width:760px\)/, 'Accounts sub-menu และรายละเอียดบัญชีต้องรองรับหน้าจอมือถือ');

console.log('admin account management contract: PASS');
