const fs = require('fs');
const assert = require('assert');

const admin = fs.readFileSync('admin/admin-app.js', 'utf8');
const accounts = fs.readFileSync('admin/accounts.html', 'utf8');
const profile = fs.readFileSync('admin/profile.html', 'utf8');
const styles = fs.readFileSync('admin/admin-accounts.css', 'utf8');

assert.match(admin, /accounts:\s*\(\)\s*=>\s*operationsV2\('admins'\)/, 'accounts.html ต้อง dispatch เข้า Account Control Plane แทน login fallback');
assert.match(admin, /async function operationsV2\(defaultFeature = 'rider-applications'\)/, 'Account Control Plane ต้องรับ default feature สำหรับ route Accounts');
for (const role of ["'admin'", "'customer'", "'store_owner'", "'rider'"]) assert.match(admin, new RegExp(`\\[${role},`), `ต้องมีเมนูบัญชี role ${role}`);
assert.match(admin, /ผู้ดูแล.*ลูกค้า.*เจ้าของร้าน.*ไรเดอร์/, 'ต้องมีเมนูรองแยกผู้ดูแล ลูกค้า เจ้าของร้าน และไรเดอร์');
assert.match(admin, /action: 'list_user_control_plane'/, 'Account Management ต้องอ่านข้อมูลจริงจาก central control plane');
assert.match(admin, /canManageAdmin = result\.can_manage_admin === true/, 'Accounts UI ต้องใช้ capability จาก backend ไม่เดาสิทธิ์ Master/Owner เอง');
assert.match(admin, /role === 'admin' && !canManageAdmin \? ' disabled' : ''/, 'Regular Admin ต้องแก้หรือ grant admin role ไม่ได้จาก UI');
assert.match(admin, /action: 'create_managed_account'/, 'ต้องสร้างบัญชี Admin/Customer ผ่าน central access function');
assert.match(admin, /การสร้างบัญชีผู้ดูแลทำได้โดย Master\/Owner เท่านั้น/, 'UI ต้องอธิบายข้อจำกัดการสร้าง Admin ให้ชัดเจน');
assert.match(admin, /action: 'update_user_profile_section'/, 'ต้องแก้ข้อมูลบัญชีผ่าน Edge Function กลางและบันทึกเฉพาะหมวดข้อมูล');
assert.match(admin, /action: 'set_user_roles'/, 'ต้องแก้ role ผ่าน central access function');
assert.match(admin, /action: 'set_account_control'/, 'ต้องจัดการสถานะ/สิทธิ์ผ่าน central access function');
assert.match(admin, /action: 'adjust_customer_wallet'/, 'การปรับยอด wallet ต้องผ่าน audit-capable central access function');
assert.match(admin, /admin_action_audit\?select=action,reason,actor_id,created_at/, 'รายละเอียดบัญชีต้องโหลด audit history ของบัญชีนั้นจากข้อมูลจริง');
assert.match(admin, /สร้างเมื่อ/, 'รายละเอียดบัญชีต้องแสดงวันสร้างจากข้อมูลจริง');
assert.match(admin, /data-account-action="roles"/, 'รายละเอียดบัญชีต้องมีทางลัดเปลี่ยนบทบาท');
assert.match(admin, /data-account-action="controls"/, 'รายละเอียดบัญชีต้องมีทางลัดเปลี่ยนสถานะและสิทธิ์');
assert.match(admin, /href="stores\.html"/, 'บัญชีร้านค้าต้องเชื่อมไปยัง Store Control Plane');
assert.match(admin, /href="riders\.html"/, 'บัญชี Rider ต้องเชื่อมไปยัง Rider Control Plane');
assert.match(accounts, /data-page="accounts"/, 'Accounts route ต้องคงเป็น MPA route เดิม');
assert.match(accounts, /admin-accounts\.css\?v=accounts-v2/, 'Accounts route ต้อง cache-bust style รายละเอียดบัญชีใหม่');
assert.match(accounts, /admin-app\.js\?v=admin-source-v12/, 'Accounts route ต้อง cache-bust runtime source ล่าสุด');
assert.doesNotMatch(accounts, /admin-override-governance\.js|admin-control-plane-patch\.js/, 'Accounts route ต้องไม่โหลด governance/control-plane overlay ที่ย้ายเข้า source หลักแล้ว');
assert.doesNotMatch(accounts, /admin-user-compact-ui\.(css|js)/, 'Accounts route ต้องไม่โหลด compact overlay ที่ถูกถอดออก');
assert.match(profile, /data-page="profile"/, 'ปุ่ม Profile ต้องเปิด current-admin profile ที่ตรงข้อความของ navigation');
assert.match(profile, /admin-profile\.css\?v=admin-profile-v1/, 'Profile route ต้องโหลด style สำหรับข้อมูลบัญชีปัจจุบัน');
assert.match(admin, /async function profile\(\)/, 'Profile route ต้องมี renderer อยู่ใน admin-app.js source หลัก');
assert.doesNotMatch(profile, /admin-control-plane-patch\.js|admin-override-governance\.js/, 'Profile route ต้องไม่โหลด control-plane/override overlay หลังย้าย source');
assert.match(profile, /admin-app\.js\?v=admin-source-v12/, 'Profile route ต้อง cache-bust runtime source ล่าสุด');
assert.match(admin, /data-user-manage/, 'รายการบัญชีต้องมีปุ่มจัดการจาก source หลัก');
assert.match(admin, /openAccountActionMenu/, 'action menu ต้องอยู่ใน source หลัก ไม่ใช่ไฟล์ overlay');
assert.match(admin, /data-account-menu-action/, 'action menu ต้องมี handler สำหรับการจัดการบัญชี');
assert.match(styles, /\.admin-account-type-menu/, 'ต้องมี responsive style ของเมนูประเภทบัญชี');
assert.match(styles, /\.admin-account-detail-list/, 'ต้องมีสไตล์รายการรายละเอียดบัญชี');
assert.match(styles, /\.mpa-modal \.mpa-table-wrap/, 'audit table ต้องเลื่อนแนวนอนได้ใน modal');
assert.match(styles, /@media\(max-width:760px\)/, 'Accounts sub-menu และรายละเอียดบัญชีต้องรองรับหน้าจอมือถือ');

console.log('admin account management contract: PASS');
