const assert = require('node:assert/strict');
const fs = require('node:fs');
const source = fs.readFileSync('admin/admin-control-plane-patch.js', 'utf8');
const css = fs.readFileSync('admin/admin-orders.css', 'utf8');
assert.match(source, /data-detail-order/, 'รายการ Orders ต้องมีปุ่มเปิด Detail');
assert.match(source, /openOrderDetail/, 'Orders ต้องมีเมนู Detail กลาง');
assert.match(source, /data-detail-status/, 'Detail ต้องมีคำสั่งเปลี่ยนสถานะ');
assert.match(source, /data-detail-edit/, 'Detail ต้องมีคำสั่งแก้รายการ');
assert.match(source, /data-detail-assign/, 'Detail ต้องมีคำสั่งเลือก Rider');
assert.match(source, /data-detail-dispatch/, 'Detail ต้องมีคำสั่ง Dispatch/ETA');
assert.match(source, /data-detail-history/, 'Detail ต้องมีเมนูประวัติ');
assert.match(source, /workState/, 'รายการต้องคำนวณสถานะการจัดการแยกจากสถานะออเดอร์');
assert.match(source, /workRank/, 'งานที่ยังค้างต้องถูกเรียงไว้ก่อนงานที่เสร็จแล้ว');
assert.match(css, /\.admin-order-row/, 'CSS ต้องรองรับรายการแบบย่อ');
assert.match(css, /\.admin-order-detail-actions/, 'CSS ต้องรองรับ action menu ใน Detail');
assert.match(css, /\.admin-order-work-attention/, 'งานใหม่/งานค้างต้องเป็นสีแดง');
assert.match(css, /\.admin-order-work-progress/, 'งานระหว่างดำเนินการต้องเป็นสีส้ม');
assert.match(css, /\.admin-order-work-done/, 'งานที่จัดการแล้วต้องเป็นสีเขียว');
console.log('admin_orders_detail_menu_contract_test: PASS');
