const assert = require('assert');
const fs = require('fs');
const patch = fs.readFileSync('performance_optimization_patch.js', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');

assert.match(patch, /requestCache = new Map/, 'ต้องมีแคชคำขอข้อมูล');
assert.match(patch, /requestInflight = new Map/, 'ต้องรวมคำขอที่กำลังโหลดซ้ำ');
assert.match(patch, /CACHE_TTL_MS = 8000/, 'ต้องมี TTL ที่จำกัดเพื่อไม่ให้ข้อมูลค้างนาน');
assert.match(patch, /method === 'GET'/, 'ต้องแคชเฉพาะคำขออ่านข้อมูล');
assert.match(patch, /if \(!cacheable\)\s*\{\s*invalidate\(path\)/, 'คำขอเขียนต้องล้างแคชที่เกี่ยวข้อง');
assert.match(patch, /catalogState\.inflight/, 'ต้อง dedupe การโหลด catalog');
assert.match(patch, /hasStoreMedia/, 'ต้องตรวจ media ก่อนบันทึกกลับ cache');
assert.match(patch, /if \(hasStoreMedia\) storage\?\.save\?\.\(\)/, 'ต้อง queue save หลัง catalog โหลดเพื่อกู้ภาพกลับ');
assert.match(patch, /marketplaceState\.inflight/, 'ต้อง dedupe การโหลดตลาด');
assert.match(patch, /storage\.save = \(\) =>/, 'ต้องรวมการบันทึก localStorage ที่เกิดถี่');
const storage = fs.readFileSync('modules/core/storage.js', 'utf8');
const bridge = fs.readFileSync('modules/legacy-bridge.js', 'utf8');
assert.match(storage, /const isMediaState = key === 'apcx_stores' \|\| key === 'apcx_config'/, 'storage module ต้องรู้จัก media state โดยไม่ลบภาพ');
assert.match(storage, /const serialized = JSON\.stringify\(value\)/, 'storage module ต้อง serialize media เดิมเพื่อคงภาพใน UI');
assert.match(storage, /preserving existing media/, 'storage module ต้องรักษาภาพเมื่อ quota เต็ม');
assert.match(storage, /export function stripInlineImages/, 'legacy media sanitizer ต้องยังอยู่เฉพาะสำหรับ caller ที่ต้องการโดยสมัครใจ');
assert.match(storage, /export function persistMediaCache/, 'ต้องมี cache media compaction แยกจาก runtime state');
assert.match(storage, /compressImageForUpload/, 'cache media ต้องใช้ตัวบีบอัดภาพเดิมของระบบ');
assert.match(storage, /STORE_CACHE_IMAGE_MAX_BYTES = 120000/, 'สำเนา media ใน cache ต้องลดขนาด');
assert.doesNotMatch(storage, /const cacheValue = shouldSanitize/, 'persist path ห้ามสร้าง cache copy ที่ลบภาพ');
assert.doesNotMatch(storage, /return ''[;\n].*isInlineImage/, 'compaction ห้ามแทนภาพ runtime ด้วยค่าว่าง');
assert.match(bridge, /core\/storage\.js\?v=performance-v5-media-preserve/, 'ต้อง cache bust storage module');
assert.match(patch, /setTimeout\(flush, 140\)/, 'ต้องหน่วงการ serialize เพื่อไม่บล็อกการกดปุ่มทันที');
assert.match(html, /catalog_stores\?select=id,name,emoji,image_url/, 'catalog ต้องจำกัดฟิลด์ที่โหลด');
assert.match(html, /catalog_menu_items\?select=id,store_id,name,emoji,image_url/, 'เมนูต้องจำกัดฟิลด์ที่โหลด');
assert.doesNotMatch(html, /\n\s*Marketplace\.refresh\(\);\n\s*updateFoodDeliveryUI/, 'หน้าแรกต้องไม่โหลดตลาดทันทีตอนบูต');
assert.match(html, /if\(name==='marketplace'\)\{renderMarketplace\(\);if\(!Marketplace\.listings\.length\)setTimeout\(\(\)=>Marketplace\.refresh\(\)/, 'ตลาดต้องโหลดแบบ background หลังเปิดหน้าจริง');
const boot = fs.readFileSync('modules/boot.js', 'utf8');
assert.match(boot, /performance_optimization_patch\.js\?v=performance-v4-media-preserve/, 'ต้องโหลด performance patch หลัง bridge พร้อม');
assert.doesNotMatch(html, /apservice:performance-ready[\s\S]*runInitialCatalog/, 'performance-ready ต้องไม่ผูกกับ eager catalog boot');
assert.match(html, /modules\/boot\.js\?v=admin-media-preserve-v3/, 'ต้อง cache bust module boot');
console.log('performance optimization contract: PASS');
