const fs = require('fs');
const assert = require('assert');
const patch = fs.readFileSync('withdrawal_proof_viewer_modal_patch.js', 'utf8');
const page = fs.readFileSync('index.html', 'utf8');
assert.match(patch, /id = 'withdrawalProofViewer'/, 'ต้องมี modal ดูหลักฐานภายในหน้าเว็บ');
assert.match(patch, /window\.viewWithdrawalProof = requestId => viewInApp/, 'ปุ่มดูหลักฐานต้องถูกผูกกับตัวแสดงผลภายในหน้าเว็บ');
assert.match(patch, /URL\.createObjectURL/, 'ต้องใช้ object URL จาก Private Storage ภายในเว็บ');
assert.doesNotMatch(patch, /window\.open\(/, 'ตัวแสดงผลใหม่ห้ามเปิดแท็บใหม่');
assert.match(patch, /closeWithdrawalProofViewer/, 'ต้องมีทางปิด modal และคืนหน่วยความจำ');
assert.match(page, /withdrawal_proof_viewer_modal_patch\.js/, 'หน้าเว็บต้องโหลดแพตช์ modal หลังแพตช์ถอนเงิน');
console.log('withdrawal proof viewer modal contract: PASS');
