(() => {
  'use strict';
  const M = window.APServiceMPA;
  const C = window.APServiceCore;
  const $ = selector => document.querySelector(selector);
  const h = M.ui.escapeHtml;
  const page = document.body.dataset.page;
  const pageScope = name => { const scope = M.network.createScope(name); addEventListener('pagehide', () => scope.dispose(), { once: true }); return scope; };
  const icons = { dashboard: '<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/>', orders: '<path d="M6 3h12v18H6zM9 7h6M9 11h6M9 15h4"/>', stores: '<path d="M4 10h16v10H4zM3 10l2-6h14l2 6M8 20v-6h8v6"/>', promotions: '<path d="M4 7h16v10H4zM4 9l16 6M8 5v4M16 5v4"/>', customers: '<path d="M9 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM3 20c.5-4 2.5-6 6-6s5.5 2 6 6M17 11a2.5 2.5 0 1 0 0-5M17 14c2.3 0 3.7 1.4 4 4"/>', riders: '<path d="M7 5h6l1 5H8zM5 20h14M7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM17 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM5 16l2-6h8l2 6"/>', finance: '<path d="M4 7h16v13H4zM4 10h16M8 16h4"/><path d="M7 4h10"/>', notifications: '<path d="M6 17h12l-1.5-2.5V10a4.5 4.5 0 0 0-9 0v4.5zM10 20h4"/>', workspace: '<path d="M4 5h16v12H4zM7 9h10M7 13h6"/><path d="m15 19 2 2 4-5"/>', settings: '<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0 6ZM4.5 13.5v-3l2-.7.7-1.7-1-2 2.1-2.1 2 1 1.7-.7.7-2h3l.7 2 1.7.7 2-1L19.7 8l-1 2 .7 1.7 2 .7v3l-2 .7-.7 1.7 1 2-2.1 2.1-2-1-1.7.7-.7 2h-3l-.7-2-1.7-.7-2 1L4.3 17l1-2-.8-1.5z"/>', legacy: '<path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5"/>', account: '<circle cx="12" cy="8" r="3"/><path d="M5 21c.8-4.2 3.1-6 7-6s6.2 1.8 7 6"/>', more: '<circle cx="5" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="19" cy="12" r="1.4"/>' };
  const icon = key => `<svg class="admin-nav-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${icons[key] || icons.dashboard}</svg>`;
  const links = [['dashboard','ภาพรวม','dashboard'],['orders','ออร์เดอร์','orders'],['stores','ร้านค้า','stores'],['riders','ไรเดอร์','riders'],['customers','ลูกค้า','customers'],['finance','การเงิน','finance'],['notifications','แจ้งเตือน','notifications'],['promotions','โฆษณา','promotions'],['ai-workspace','AI Workspace','workspace'],['settings','ตั้งค่ากลาง','settings']];
  const badgeKeys = { orders: 'orders', finance: 'finance', notifications: 'notifications' };
  const navLink = (key, label, iconKey, active, extra = '') => `<a class="admin-nav-link${key===active?' active':''}${extra}" href="${key}.html" title="${h(label)}" aria-label="${h(label)}"${key===active?' aria-current="page"':''}>${icon(iconKey)}<span>${h(label)}</span>${badgeKeys[key] ? `<b class="admin-nav-badge" data-admin-badge="${badgeKeys[key]}" hidden>0</b>` : ''}</a>`;
  const navGroup = (title, items, active) => `<section class="admin-nav-group" aria-label="${h(title)}"><p>${h(title)}</p>${items.map(([key,label,iconKey]) => navLink(key,label,iconKey,active,' admin-nav-popover-link')).join('')}</section>`;
  const legacyLinks = [['rider-applications','ใบสมัครไรเดอร์'],['settlements','รายได้และกระทบยอด'],['support','ศูนย์ช่วยเหลือ'],['inventory','สินค้าและสต็อก'],['content','เนื้อหาเดิม'],['admins','ผู้ดูแลเดิม'],['errors','ศูนย์ข้อผิดพลาด'],['mapping','การจับคู่ข้อมูล']];
  const nav = active => { const primary = links.slice(0, 5), operations = links.slice(5, 7), content = links.slice(7, 8), system = links.slice(8); return `<header class="mpa-topbar admin-topbar"><div class="admin-topbar-inner"><a class="mpa-brand admin-brand" href="dashboard.html" aria-label="AP Service ศูนย์ควบคุมหลังบ้าน"><span class="admin-brand-mark">AP</span><span><b>AP Service</b><small>ศูนย์ควบคุม</small></span></a><nav class="mpa-nav admin-nav" aria-label="เมนูผู้ดูแลระบบ"><div class="admin-nav-primary">${primary.map(([key,label,iconKey]) => navLink(key,label,iconKey,active)).join('')}</div><details class="admin-nav-more"><summary title="เมนูเพิ่มเติม" aria-label="เมนูเพิ่มเติม">${icon('more')}<span>เพิ่มเติม</span></summary><div class="admin-nav-popover">${navGroup('การปฏิบัติงาน', operations, active)}${navGroup('เนื้อหาและสื่อ', content, active)}${navGroup('ระบบ', system, active)}<section class="admin-nav-group admin-nav-group-legacy" aria-label="ระบบเดิมที่ยังใช้งานได้"><p>ฟังก์ชันเดิมระหว่างย้าย</p>${legacyLinks.map(([key,label]) => `<a class="admin-nav-legacy" href="../admin.html?admin=${encodeURIComponent(key)}" title="เปิด ${h(label)} ในระบบเดิม" aria-label="เปิด ${h(label)} ในระบบเดิม">${icon('legacy')}<span>${h(label)}</span></a>`).join('')}</section></div></details><a class="admin-account-link" href="settings.html" title="บัญชีและตั้งค่ากลาง" aria-label="บัญชีและตั้งค่ากลาง">${icon('account')}<span>บัญชี</span></a></nav></div></header>`; };
  const app = (active, content) => { document.body.innerHTML = `${nav(active)}<main class="mpa-shell" data-page-content>${content}</main>`; };
  const adminBadgeStorageKey = 'apservice-admin-nav-badges-v1';
  const adminBadgeRefreshKey = 'apservice-admin-nav-badges-refreshed-at-v1';
  const adminBadgeTtlMs = 20_000;
  const paintNavBadges = values => { Object.entries(values || {}).forEach(([key, value]) => document.querySelectorAll(`[data-admin-badge="${key}"]`).forEach(node => { const count = Math.max(0, Number(value || 0)); node.textContent = count > 99 ? '99+' : String(count); node.hidden = !count; })); };
  const startNavBadges = () => { try { paintNavBadges(JSON.parse(sessionStorage.getItem(adminBadgeStorageKey) || '{}')); } catch (_) {} const refreshedAt = Number(sessionStorage.getItem(adminBadgeRefreshKey) || 0); if (document.hidden || Date.now() - refreshedAt < adminBadgeTtlMs) return; setTimeout(async () => { try { const [orders, finance, notifications] = await Promise.all([countRows('delivery_orders?select=id&status=neq.สำเร็จแล้ว', M.requestCount, 'admin-nav:orders'), countRows('withdrawal_requests?select=id&status=eq.pending', M.requestCount, 'admin-nav:finance').catch(() => 0), countRows('mobile_notifications?select=id&read_at=is.null', M.requestCount, 'admin-nav:notifications').catch(() => 0)]); const values = { orders, finance, notifications }; paintNavBadges(values); sessionStorage.setItem(adminBadgeStorageKey, JSON.stringify(values)); sessionStorage.setItem(adminBadgeRefreshKey, String(Date.now())); } catch (_) { /* Cached values remain visible; badge failures never block a route. */ } }, 0); };
  const countRows = async (path, requestCount = M.requestCount, cacheKey = '') => requestCount(path, { private: true, cacheTtlMs: 15_000, cacheKey });
  const dashboardCounts = async requestCount => Promise.all([
    countRows('delivery_orders?select=id&status=neq.สำเร็จแล้ว', requestCount, 'admin-count:active-orders'),
    countRows('stores?select=id&active=eq.true', requestCount, 'admin-count:active-stores'),
    countRows('riders?select=id&status=eq.พร้อมรับงาน', requestCount, 'admin-count:available-riders'),
    countRows('withdrawal_requests?select=id&status=eq.pending', requestCount, 'admin-count:pending-withdrawals').catch(() => 0),
  ]);
  async function gate(active, content) {
    app(active, content);
    const access = await M.auth.requireRole('admin', { loginUrl: 'index.html', container: $('[data-page-content]'), renderLoading: false });
    if (access) startNavBadges();
    return access;
  }
  async function login() {
    document.body.innerHTML = `<main class="mpa-shell" style="min-height:100vh;display:grid;place-items:center" data-page-content>${M.ui.loading('กำลังเปิดศูนย์ควบคุมหลังบ้าน…')}</main>`;
    const signedInUser = await M.auth.currentUser();
    if (signedInUser) {
      const roles = await M.auth.rolesFor(signedInUser.id).catch(() => []);
      if (roles.includes('admin')) { location.replace('dashboard.html'); return; }
    }
    document.body.innerHTML = `<main class="mpa-shell" style="min-height:100vh;display:grid;place-items:center"><section class="mpa-card" style="width:min(430px,100%)"><div style="text-align:center"><div style="width:48px;height:48px;border-radius:16px;margin:auto;display:grid;place-items:center;background:#0b8c7c;color:#fff;font-weight:950">AP</div><h1>เข้าสู่ศูนย์ควบคุมหลังบ้าน</h1><p class="mpa-muted">เข้าสู่ระบบด้วยบัญชีที่ได้รับสิทธิ์ Admin ใน Supabase</p></div><form id="loginForm"><div class="mpa-field"><label>อีเมล</label><input id="email" type="email" autocomplete="email" autofocus required></div><div class="mpa-field"><label>รหัสผ่าน</label><input id="password" type="password" autocomplete="current-password" required></div><button class="mpa-button" style="width:100%">เข้าสู่หลังบ้าน</button></form><p class="mpa-muted" style="text-align:center;margin:16px 0 0"><a href="../admin.html">เปิดระบบเดิม (fallback)</a></p></section></main>`;
    $('#loginForm').onsubmit = async event => { event.preventDefault(); try { const session = await M.auth.signIn($('#email').value.trim(), $('#password').value); const roles = await M.auth.rolesFor(session.user.id); if (!roles.includes('admin')) { M.auth.signOut('index.html'); throw new Error('บัญชีนี้ไม่มีสิทธิ์ Admin'); } location.assign('dashboard.html'); } catch (error) { M.ui.setNotice(error.message, 'error'); } };
  }
  async function dashboard() {
    const access = await gate('dashboard', `<div class="mpa-page-head"><div><h1>ภาพรวมงานหลังบ้าน</h1><p>เปลี่ยนหน้าแล้วแสดง shell ทันที จากนั้นโหลดสรุปข้อมูลแบบ background</p></div><button class="mpa-button mpa-button-secondary" id="signOut">ออกจากระบบ</button></div><section class="admin-quick-actions" aria-label="ทางลัดงานสำคัญ"><a href="stores.html" class="admin-quick-action">${icon('stores')}<span>เพิ่มหรือจัดการร้าน</span></a><a href="promotions.html" class="admin-quick-action">${icon('promotions')}<span>เพิ่มโฆษณา</span></a><a href="orders.html" class="admin-quick-action">${icon('orders')}<span>ตรวจออร์เดอร์ค้าง</span></a><a href="finance.html" class="admin-quick-action">${icon('finance')}<span>ตรวจการเงิน</span></a></section><div class="mpa-grid stats" id="stats">${M.ui.loading('กำลังสรุปงานค้าง…')}</div><section class="mpa-card" style="margin-top:18px"><h2 style="margin-top:0">งานที่ต้องตรวจสอบ</h2><div id="pending">${M.ui.loading('กำลังอ่านรายการล่าสุด…')}</div></section>`); if (!access) return;
    $('#signOut').onclick = () => M.auth.signOut('index.html');
    const scope = pageScope('admin:dashboard'); let lastSignature = '';
    const render = counts => { const signature = JSON.stringify(counts); if (signature === lastSignature) return; lastSignature = signature; const [orders, stores, riders, withdrawals] = counts; $('#stats').innerHTML = `<a class="mpa-card mpa-stat admin-stat-link" href="orders.html"><small>ออร์เดอร์ที่ยังดำเนินการ</small><strong>${orders}</strong><span>เปิดออร์เดอร์</span></a><a class="mpa-card mpa-stat admin-stat-link" href="stores.html"><small>ร้านค้าเปิดบริการ</small><strong>${stores}</strong><span>เปิดร้านค้า</span></a><a class="mpa-card mpa-stat admin-stat-link" href="riders.html"><small>ไรเดอร์พร้อมรับงาน</small><strong>${riders}</strong><span>เปิดไรเดอร์</span></a><a class="mpa-card mpa-stat admin-stat-link" href="finance.html"><small>คำขอถอนเงินรอตรวจ</small><strong>${withdrawals}</strong><span>เปิดการเงิน</span></a>`; $('#pending').innerHTML = `<p class="mpa-muted">ใช้เมนู <a href="orders.html">ออร์เดอร์</a>, <a href="finance.html">การเงิน</a> และ <a href="settings.html">ตั้งค่ากลาง</a> เพื่อดำเนินงานแต่ละประเภท ข้อมูลนี้รีเฟรชภายหลัง shell แสดงแล้ว จึงไม่ block navigation</p>`; };
    try { render(await dashboardCounts(scope.requestCount)); } catch (err) { if (err.code !== M.network.STALE_RESPONSE) $('#stats').innerHTML = M.ui.error('โหลดสรุปไม่สำเร็จ', err.message); return; }
    const stop = M.network.startBackgroundSync({ key: 'admin-dashboard-counts', intervalMs: 30_000, task: async () => { const counts = await dashboardCounts((path, options) => scope.requestCount(path, { ...options, forceFresh: true })); return { changed: JSON.stringify(counts) !== lastSignature, data: counts }; } });
    const originalStop = stop; addEventListener('pagehide', originalStop, { once: true });
  }
  async function orders() {
    const access = await gate('orders', `<div class="mpa-page-head"><div><h1>จัดการออร์เดอร์</h1><p>เปลี่ยนสถานะตาม Shared Core และสิทธิ์ Admin ใน RLS</p></div></div><section id="orders" class="mpa-card">${M.ui.loading('กำลังโหลดออร์เดอร์…')}</section>`); if (!access) return;
    try { const rows = await M.request('delivery_orders?select=id,store_name,customer_name,status,total,payable,ordered_at&order=ordered_at.desc&limit=150', { private: true }); const statuses = Object.values(C.contracts.orderStatus); $('#orders').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>เวลา</th><th>ร้าน/ลูกค้า</th><th>สถานะ</th><th>ยอด</th><th>เปลี่ยนสถานะ</th></tr></thead><tbody>${rows.map(row => `<tr><td>${new Date(row.ordered_at).toLocaleString('th-TH')}</td><td><b>${h(row.store_name || '-')}</b><br><span class="mpa-muted">${h(row.customer_name || '-')}</span></td><td><span class="mpa-badge">${h(row.status)}</span></td><td>${M.ui.baht(row.payable ?? row.total)}</td><td><select data-status="${h(row.id)}"><option value="">เลือกสถานะ…</option>${statuses.filter(status => status !== row.status).map(status => `<option value="${h(status)}">${h(status)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีออร์เดอร์'); document.querySelectorAll('[data-status]').forEach(select => select.onchange = async () => { if (!select.value) return; const row = rows.find(item => item.id === select.dataset.status); const check = C.order.canTransition({ from: row.status, to: select.value, actor: 'admin' }); if (!check.ok) return M.ui.setNotice(check.reason, 'error'); try { await M.request(`delivery_orders?id=eq.${encodeURIComponent(row.id)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ status: select.value, updated_at: M.ui.nowIso() }) }); M.ui.setNotice('บันทึกสถานะแล้ว'); setTimeout(() => location.reload(), 350); } catch (err) { M.ui.setNotice(err.message, 'error'); } }); } catch (err) { $('#orders').innerHTML = M.ui.error('โหลดออร์เดอร์ไม่สำเร็จ', err.message); }
  }
  async function stores() {
    const access = await gate('stores', `<div class="mpa-page-head"><div><h1>ร้านค้าและ Merchant</h1><p>ตรวจรายการร้านค้าและสถานะเปิดบริการ</p></div></div><section id="stores" class="mpa-card">${M.ui.loading('กำลังโหลดร้านค้า…')}</section>`); if (!access) return;
    const openMediaEditor = row => {
      if (!window.APServiceMedia?.uploadPublicCatalogImage) return M.ui.setNotice('ระบบอัปโหลดรูปภาพยังโหลดไม่พร้อม กรุณารีเฟรชหน้าเว็บแล้วลองใหม่', 'error');
      const dialog = document.createElement('div');
      dialog.className = 'mpa-modal-backdrop';
      dialog.innerHTML = `<section class="mpa-card mpa-modal" role="dialog" aria-modal="true" aria-label="จัดการรูปและสื่อร้าน"><div class="mpa-page-head"><div><h2 style="margin:0">รูปและสื่อ: ${h(row.name)}</h2><p>เลือกรูปจากคลังหรือกล้อง ระบบจะบีบอัดไม่เกิน 1 MB แล้วอัปโหลดและตรวจสอบ URL ก่อนบันทึก</p></div><button type="button" class="mpa-button mpa-button-secondary" data-close>ปิด</button></div><div class="mpa-grid" style="grid-template-columns:repeat(auto-fit,minmax(220px,1fr))"><label class="mpa-field">ไอคอนร้าน<input type="file" accept="image/jpeg,image/png,image/webp" data-media="image_url"><span class="mpa-muted">รองรับ JPG, PNG, WebP</span><img data-preview="image_url" ${row.image_url ? `src="${h(row.image_url)}"` : ''} alt="ตัวอย่างไอคอนร้าน" hidden></label><label class="mpa-field">ภาพพื้นหลังร้าน<input type="file" accept="image/jpeg,image/png,image/webp" data-media="background_url"><span class="mpa-muted">รองรับ JPG, PNG, WebP</span><img data-preview="background_url" ${row.background_url ? `src="${h(row.background_url)}"` : ''} alt="ตัวอย่างภาพพื้นหลังร้าน" hidden></label></div><p class="mpa-muted" data-media-status>เลือกไฟล์เพื่อเริ่มการบีบอัดและอัปโหลด</p><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button type="button" class="mpa-button mpa-button-secondary" data-close>ยกเลิก</button><button type="button" class="mpa-button" data-save-media disabled>บันทึกรูปและสื่อ</button></div></section>`;
      document.body.append(dialog);
      dialog.querySelectorAll('[data-preview]').forEach(preview => { if (preview.getAttribute('src')) preview.hidden = false; });
      const draft = { image_url: row.image_url || null, background_url: row.background_url || null };
      const status = dialog.querySelector('[data-media-status]'); const save = dialog.querySelector('[data-save-media]');
      const close = () => dialog.remove(); dialog.querySelectorAll('[data-close]').forEach(button => { button.onclick = close; });
      dialog.querySelectorAll('[data-media]').forEach(input => { input.onchange = async () => {
        const file = input.files?.[0]; const field = input.dataset.media; if (!file || !field) return;
        try {
          status.textContent = 'กำลังเริ่มตรวจสอบรูปภาพ…';
          const session = await M.auth.refreshSession(false);
          if (!session?.access_token || !session?.user?.id) throw new Error('เซสชันแอดมินหมดอายุ กรุณาเข้าสู่ระบบใหม่ก่อนอัปโหลด');
          const uploaded = await window.APServiceMedia.uploadPublicCatalogImage(file, { url: M.config.url, publishableKey: M.config.publishableKey, accessToken: session.access_token, actorId: session.user.id, scope: `store-${row.id}-${field}` });
          draft[field] = uploaded.publicUrl;
          const preview = dialog.querySelector(`[data-preview="${field}"]`); if (preview) { preview.src = uploaded.publicUrl; preview.hidden = false; }
          save.disabled = false; status.textContent = 'อัปโหลดและตรวจสอบรูปแล้ว กดบันทึกรูปและสื่อเพื่อยืนยัน';
        } catch (error) { input.value = ''; status.textContent = error.message || 'อัปโหลดรูปไม่สำเร็จ'; M.ui.setNotice(status.textContent, 'error'); }
      }; });
      save.onclick = async () => {
        save.disabled = true; status.textContent = 'กำลังบันทึก URL รูปภาพลงข้อมูลร้าน…';
        try {
          await M.request(`stores?id=eq.${encodeURIComponent(row.id)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ ...draft, updated_at: M.ui.nowIso() }) });
          M.ui.setNotice('บันทึกรูปและสื่อร้านแล้ว'); close(); setTimeout(() => location.reload(), 180);
        } catch (error) { save.disabled = false; status.textContent = error.message || 'บันทึกรูปและสื่อไม่สำเร็จ'; M.ui.setNotice(status.textContent, 'error'); }
      };
    };
    try { const rows = await M.request('stores?select=id,name,owner_email,phone,rating,eta,active,image_url,background_url&order=name.asc&limit=250', { private: true }); $('#stores').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>ร้านค้า</th><th>ติดต่อ</th><th>คะแนน</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>${rows.map(row => `<tr><td><b>${h(row.name)}</b><br><span class="mpa-muted">${h(row.eta || '')}</span></td><td>${h(row.owner_email || row.phone || '-')}</td><td>${Number(row.rating || 0).toFixed(1)}</td><td><span class="mpa-badge">${row.active ? 'เปิดบริการ' : 'ปิดบริการ'}</span></td><td style="display:flex;gap:7px;flex-wrap:wrap"><button class="mpa-button mpa-button-secondary" data-media-editor="${h(row.id)}">รูปและสื่อ</button><button class="mpa-button mpa-button-secondary" data-toggle="${h(row.id)}">${row.active ? 'ปิดร้าน' : 'เปิดร้าน'}</button></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีร้านค้า'); document.querySelectorAll('[data-media-editor]').forEach(button => button.onclick = () => openMediaEditor(rows.find(item => item.id === button.dataset.mediaEditor))); document.querySelectorAll('[data-toggle]').forEach(button => button.onclick = async () => { const row = rows.find(item => item.id === button.dataset.toggle); try { await M.request(`stores?id=eq.${encodeURIComponent(row.id)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ active: !row.active, updated_at: M.ui.nowIso() }) }); M.ui.setNotice('บันทึกสถานะร้านแล้ว'); setTimeout(() => location.reload(), 350); } catch (err) { M.ui.setNotice(err.message, 'error'); } }); } catch (err) { $('#stores').innerHTML = M.ui.error('โหลดร้านค้าไม่สำเร็จ', err.message); }
  }
  async function promotions() {
    const access = await gate('promotions', `<div class="mpa-page-head"><div><h1>ภาพโฆษณาหน้าแรก</h1><p>บีบอัด อัปโหลด ตรวจ URL และบันทึกเป็นการตั้งค่ากลางก่อนแสดงหน้าแรกของลูกค้า</p></div></div><section id="promotions" class="mpa-card">${M.ui.loading('กำลังโหลดรายการโฆษณา…')}</section>`); if (!access) return;
    const host = $('#promotions');
    const normalize = value => Array.isArray(value) ? value : Array.isArray(value?.items) ? value.items : [];
    let items = [];
    const render = () => {
      host.innerHTML = `<div class="mpa-page-head"><div><h2 style="margin:0">รายการโฆษณา</h2><p>เปิดแสดงเฉพาะรายการที่มีภาพและเปิดใช้งาน</p></div><button class="mpa-button mpa-button-secondary" type="button" data-add-promotion>เพิ่มโฆษณา</button></div><div class="mpa-grid">${items.length ? items.map((item, index) => `<article class="mpa-card" style="box-shadow:none"><div class="mpa-page-head"><div><h3 style="margin:0">โฆษณาที่ ${index + 1}</h3><p class="mpa-muted">${item.image_url ? 'อัปโหลดรูปแล้ว' : 'ยังไม่มีรูปภาพ'}</p></div><button class="mpa-button mpa-button-secondary" type="button" data-delete-promotion="${h(item.id)}">ลบ</button></div><div class="mpa-grid" style="grid-template-columns:repeat(auto-fit,minmax(190px,1fr))"><label class="mpa-field">หัวข้อ<input data-promotion-field="title" data-promotion-id="${h(item.id)}" value="${h(item.title || '')}" maxlength="80"></label><label class="mpa-field">ป้ายกำกับ<input data-promotion-field="badge" data-promotion-id="${h(item.id)}" value="${h(item.badge || '')}" maxlength="24"></label><label class="mpa-field">รายละเอียด<input data-promotion-field="description" data-promotion-id="${h(item.id)}" value="${h(item.description || '')}" maxlength="180"></label><label class="mpa-field">เปิดแสดง<select data-promotion-field="active" data-promotion-id="${h(item.id)}"><option value="true" ${item.active !== false ? 'selected' : ''}>เปิด</option><option value="false" ${item.active === false ? 'selected' : ''}>ปิด</option></select></label><label class="mpa-field">รูปภาพ (JPG, PNG, WebP)<input type="file" accept="image/jpeg,image/png,image/webp" data-promotion-file="${h(item.id)}"><span class="mpa-muted">แสดงความคืบหน้าระหว่างบีบอัดและอัปโหลด</span></label><div class="mpa-field"><label>ตัวอย่างภาพ</label>${item.image_url ? `<img style="width:100%;height:150px;object-fit:cover;border:1px solid var(--ap-line);border-radius:10px" src="${h(item.image_url)}" alt="ตัวอย่างโฆษณา">` : '<div class="mpa-muted" style="padding:16px;border:1px dashed var(--ap-line);border-radius:10px">ยังไม่มีภาพ</div>'}</div></div></article>`).join('') : M.ui.empty('ยังไม่มีโฆษณา กด “เพิ่มโฆษณา” เพื่อสร้างรายการแรก')}</div><div style="display:flex;justify-content:flex-end;margin-top:16px"><button type="button" class="mpa-button" data-save-promotions ${items.some(item => !item.image_url) ? 'disabled title="ทุกรายการต้องมีรูปก่อนบันทึก"' : ''}>บันทึกหน้าเว็บและสื่อ</button></div>`;
      host.querySelector('[data-add-promotion]')?.addEventListener('click', () => { const id = typeof crypto?.randomUUID === 'function' ? crypto.randomUUID() : `promo-${Date.now()}`; items.push({ id, title: '', badge: 'AD', description: '', image_url: '', active: true }); render(); });
      host.querySelectorAll('[data-delete-promotion]').forEach(button => button.addEventListener('click', () => { items = items.filter(item => item.id !== button.dataset.deletePromotion); render(); }));
      host.querySelectorAll('[data-promotion-field]').forEach(input => input.addEventListener('input', () => { const item = items.find(row => row.id === input.dataset.promotionId); if (item) item[input.dataset.promotionField] = input.dataset.promotionField === 'active' ? input.value === 'true' : input.value; }));
      host.querySelectorAll('[data-promotion-file]').forEach(input => input.addEventListener('change', async () => {
        const file = input.files?.[0]; const item = items.find(row => row.id === input.dataset.promotionFile); if (!file || !item) return;
        try { const session = await M.auth.refreshSession(false); if (!session?.access_token || !session?.user?.id) throw new Error('เซสชันแอดมินหมดอายุ กรุณาเข้าสู่ระบบใหม่ก่อนอัปโหลด'); const uploaded = await window.APServiceMedia.uploadPublicCatalogImage(file, { url: M.config.url, publishableKey: M.config.publishableKey, accessToken: session.access_token, actorId: session.user.id, scope: `promotion-${item.id}` }); item.image_url = uploaded.publicUrl; render(); M.ui.setNotice('อัปโหลดภาพโฆษณาแล้ว กดบันทึกหน้าเว็บและสื่อเพื่อเผยแพร่'); } catch (error) { input.value = ''; M.ui.setNotice(error.message || 'อัปโหลดภาพโฆษณาไม่สำเร็จ', 'error'); }
      }));
      host.querySelector('[data-save-promotions]')?.addEventListener('click', async () => { try { await M.request('platform_configs?on_conflict=key', { method: 'POST', private: true, headers: { Prefer: 'resolution=merge-duplicates,return=minimal' }, body: JSON.stringify({ key: 'customer_promotions', value: { items }, updated_at: M.ui.nowIso() }) }); M.ui.setNotice('บันทึกหน้าเว็บและสื่อแล้ว รายการจะแสดงในหน้าแรกของลูกค้า'); } catch (error) { M.ui.setNotice(error.message || 'บันทึกโฆษณาไม่สำเร็จ', 'error'); } });
    };
    try { const rows = await M.request('platform_configs?select=key,value&key=eq.customer_promotions&limit=1', { private: true }); items = normalize(rows?.[0]?.value); render(); } catch (error) { host.innerHTML = M.ui.error('โหลดโฆษณาไม่สำเร็จ', error.message); }
  }
  async function customers() {
    const access = await gate('customers', `<div class="mpa-page-head"><div><h1>ลูกค้าและโปรไฟล์</h1><p>อ่านข้อมูลตาม RLS ของ Admin</p></div></div><section id="customers" class="mpa-card">${M.ui.loading('กำลังโหลดลูกค้า…')}</section>`); if (!access) return;
    try { const rows = await M.request('user_profiles?select=user_id,display_name,email,phone,created_at&order=created_at.desc&limit=250', { private: true }); $('#customers').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>โทรศัพท์</th><th>เริ่มใช้งาน</th></tr></thead><tbody>${rows.map(row => `<tr><td>${h(row.display_name || '-')}</td><td>${h(row.email || '-')}</td><td>${h(row.phone || '-')}</td><td>${row.created_at ? new Date(row.created_at).toLocaleDateString('th-TH') : '-'}</td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีข้อมูลลูกค้า'); } catch (err) { $('#customers').innerHTML = M.ui.error('โหลดข้อมูลลูกค้าไม่สำเร็จ', err.message); }
  }
  async function riders() {
    const access = await gate('riders', `<div class="mpa-page-head"><div><h1>ไรเดอร์และการปฏิบัติงาน</h1><p>ติดตามสถานะและข้อมูลผู้จัดส่ง</p></div></div><section id="riders" class="mpa-card">${M.ui.loading('กำลังโหลดไรเดอร์…')}</section>`); if (!access) return;
    try { const rows = await M.request('riders?select=id,name,phone,vehicle,status,updated_at&order=name.asc&limit=250', { private: true }); $('#riders').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>ชื่อ</th><th>โทรศัพท์</th><th>ยานพาหนะ</th><th>สถานะ</th></tr></thead><tbody>${rows.map(row => `<tr><td>${h(row.name)}</td><td>${h(row.phone || '-')}</td><td>${h(row.vehicle || '-')}</td><td><span class="mpa-badge">${h(row.status || '-')}</span></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีข้อมูลไรเดอร์'); } catch (err) { $('#riders').innerHTML = M.ui.error('โหลดข้อมูลไรเดอร์ไม่สำเร็จ', err.message); }
  }
  async function finance() {
    const access = await gate('finance', `<div class="mpa-page-head"><div><h1>การเงินและคำขอถอน</h1><p>ตรวจสลิปแบบ in-app และติดตามคำขอถอนเงินตามสิทธิ์ Admin</p></div></div><section id="finance" class="mpa-card">${M.ui.loading('กำลังโหลดคิวการเงิน…')}</section>`); if (!access) return;
    const host = $('#finance');
    const orderOf = review => Array.isArray(review.delivery_orders) ? review.delivery_orders[0] || {} : review.delivery_orders || {};
    const showSlip = async review => {
      try {
        if (!window.APServiceMedia?.createSignedImageUrl) throw new Error('ระบบเปิดสลิปยังโหลดไม่พร้อม กรุณารีเฟรชแล้วลองใหม่');
        const rawPath = String(review.slip_path || ''); const path = rawPath.replace(/^payment-slips\//, ''); if (!path) throw new Error('ไม่พบตำแหน่งจัดเก็บสลิป');
        const session = await M.auth.refreshSession(false); if (!session?.access_token) throw new Error('เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่');
        const signedUrl = await window.APServiceMedia.createSignedImageUrl({ url: M.config.url, publishableKey: M.config.publishableKey, accessToken: session.access_token, bucket: 'payment-slips', path });
        const modal = document.createElement('div'); modal.className = 'mpa-modal-backdrop'; modal.innerHTML = `<section class="mpa-card mpa-modal" role="dialog" aria-modal="true" aria-label="ดูสลิปชำระเงิน"><div class="mpa-page-head"><div><h2 style="margin:0">สลิปออร์เดอร์ ${h(review.order_id)}</h2><p class="mpa-muted">URL สำหรับดูรูปนี้มีอายุจำกัด และไม่เปิดออกนอกหน้าเว็บ</p></div><button class="mpa-button mpa-button-secondary" type="button" data-close>ปิด</button></div><img src="${h(signedUrl)}" alt="สลิปชำระเงิน" style="display:block;width:100%;max-height:70vh;object-fit:contain;border:1px solid var(--ap-line);border-radius:12px;background:#f8faf9" referrerpolicy="no-referrer"></section>`;
        const close = () => modal.remove(); modal.querySelector('[data-close]').onclick = close; modal.addEventListener('click', event => { if (event.target === modal) close(); }); document.body.append(modal);
      } catch (err) { M.ui.setNotice(err.message || 'เปิดสลิปไม่สำเร็จ', 'error'); }
    };
    const render = ({ reviews, withdrawals }) => {
      host.innerHTML = `<section><div class="mpa-page-head"><div><h2 style="margin:0">คิวตรวจสลิปชำระเงิน</h2><p class="mpa-muted">ตรวจยอด วันเวลา และผู้รับเงินจริงก่อนกดอนุมัติ อนุมัติแล้วจะปล่อยออร์เดอร์ให้ร้านรับงาน</p></div><button class="mpa-button mpa-button-secondary" type="button" id="refreshFinance">รีเฟรช</button></div>${reviews?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>ออร์เดอร์/ลูกค้า</th><th>ยอด/เวลา</th><th>ผลเบื้องต้น</th><th>หลักฐาน</th><th>จัดการ</th></tr></thead><tbody>${reviews.map(review => { const order = orderOf(review); return `<tr><td><b>${h(review.order_id)}</b><br><span class="mpa-muted">${h(order.customer_name || order.customer_email || '-')}</span></td><td><b>${M.ui.baht(review.expected_amount)}</b><br><span class="mpa-muted">${review.uploaded_at ? new Date(review.uploaded_at).toLocaleString('th-TH') : '-'}</span></td><td><span class="mpa-badge">${h(review.preliminary_status || 'needs_review')}</span></td><td><button class="mpa-button mpa-button-secondary" data-slip-view="${h(review.id)}">ดูสลิป</button></td><td><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="mpa-button" data-slip-approve="${h(review.id)}">อนุมัติ</button><button class="mpa-button mpa-button-secondary" data-slip-retry="${h(review.id)}">ขอแนบใหม่</button></div></td></tr>`; }).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีสลิปรอตรวจสอบ')}</section><section style="margin-top:24px"><h2>คำขอถอนเงิน</h2>${withdrawals?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>สร้างเมื่อ</th><th>ผู้รับเงิน</th><th>จำนวน</th><th>สถานะ</th></tr></thead><tbody>${withdrawals.map(row => `<tr><td>${row.created_at ? new Date(row.created_at).toLocaleString('th-TH') : '-'}</td><td>${h(row.requester_name || row.rider_name || row.user_name || '-')}</td><td>${M.ui.baht(row.amount || row.requested_amount || 0)}</td><td><span class="mpa-badge">${h(row.status || '-')}</span></td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ไม่มีคำขอถอนเงินที่ต้องจัดการ')}</section>`;
      host.querySelector('#refreshFinance').onclick = () => load();
      host.querySelectorAll('[data-slip-view]').forEach(button => button.onclick = () => showSlip(reviews.find(row => row.id === button.dataset.slipView)));
      const decide = async (review, approved) => {
        const order = orderOf(review); const nextStatus = approved ? C.contracts.orderStatus.STORE_ACCEPTED : C.contracts.orderStatus.PAYMENT_RETRY; const transition = C.order.canTransition({ from: order.status, to: nextStatus, actor: 'admin' });
        if (!transition.ok) return M.ui.setNotice(transition.reason, 'error');
        const baseNote = approved ? 'ตรวจสอบโดยแอดมินแล้ว' : 'กรุณาแนบสลิปใหม่ให้เห็นยอด วันที่ เวลา และชื่อผู้รับชัดเจน';
        const note = approved ? baseNote : (window.prompt('ระบุเหตุผลที่ต้องแนบสลิปใหม่ (ลูกค้าจะเห็นข้อความนี้)', baseNote) || baseNote);
        const confirmation = approved ? `ยืนยันอนุมัติสลิปและปล่อยออร์เดอร์ ${review.order_id} ให้ร้านรับงานหรือไม่?` : `ยืนยันขอให้ลูกค้าแนบสลิปใหม่สำหรับออร์เดอร์ ${review.order_id} หรือไม่?`;
        if (!window.confirm(confirmation)) return;
        try {
          await M.request(`payment_slip_reviews?id=eq.${encodeURIComponent(review.id)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ status: approved ? 'approved' : 'needs_reupload', reviewed_at: M.ui.nowIso(), reviewed_by: access.user.id, reviewer_note: note }) });
          await M.request(`delivery_orders?id=eq.${encodeURIComponent(review.order_id)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify(approved ? { status: nextStatus, payment_confirmed_at: M.ui.nowIso(), updated_at: M.ui.nowIso() } : { status: nextStatus, updated_at: M.ui.nowIso() }) });
          await M.request('order_status_events', { method: 'POST', private: true, headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ order_id: review.order_id, status: nextStatus, actor_id: access.user.id, actor_label: 'แอดมินตรวจสลิป' }) }).catch(() => {});
          M.ui.setNotice(approved ? 'อนุมัติสลิปแล้ว ระบบปล่อยออร์เดอร์ให้ร้านรับงาน' : 'ส่งคำขอแนบสลิปใหม่ให้ลูกค้าแล้ว'); load();
        } catch (err) { M.ui.setNotice(`บันทึกผลตรวจสลิปไม่สำเร็จ: ${err.message}`, 'error'); }
      };
      host.querySelectorAll('[data-slip-approve]').forEach(button => button.onclick = () => decide(reviews.find(row => row.id === button.dataset.slipApprove), true));
      host.querySelectorAll('[data-slip-retry]').forEach(button => button.onclick = () => decide(reviews.find(row => row.id === button.dataset.slipRetry), false));
    };
    const load = async () => {
      try {
        const [reviews, withdrawals] = await Promise.all([
          M.request('payment_slip_reviews?select=id,order_id,slip_path,expected_amount,status,preliminary_status,preliminary_result,uploaded_at,delivery_orders(customer_name,customer_email,payable,status)&status=eq.pending&order=uploaded_at.desc&limit=100', { private: true }),
          M.request('withdrawal_requests?select=*&order=created_at.desc&limit=150', { private: true }),
        ]);
        render({ reviews, withdrawals });
      } catch (err) { host.innerHTML = M.ui.error('โหลดข้อมูลการเงินไม่สำเร็จ', err.message); }
    };
    load();
  }
  async function notifications() {
    const access = await gate('notifications', `<div class="mpa-page-head"><div><h1>การแจ้งเตือน</h1><p>ติดตามข้อความและงานที่รอการดำเนินการ</p></div></div><section id="notifications" class="mpa-card">${M.ui.loading('กำลังโหลดการแจ้งเตือน…')}</section>`); if (!access) return;
    try { const rows = await M.request('mobile_notifications?select=id,title,body,created_at,read_at&order=created_at.desc&limit=150', { private: true }); $('#notifications').innerHTML = rows?.length ? `<div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>เวลา</th><th>หัวข้อ</th><th>ข้อความ</th><th>อ่านแล้ว</th></tr></thead><tbody>${rows.map(row => `<tr><td>${row.created_at ? new Date(row.created_at).toLocaleString('th-TH') : '-'}</td><td>${h(row.title || '-')}</td><td>${h(row.body || '-')}</td><td>${row.read_at ? 'แล้ว' : 'ยังไม่อ่าน'}</td></tr>`).join('')}</tbody></table></div>` : M.ui.empty('ยังไม่มีการแจ้งเตือน'); } catch (err) { $('#notifications').innerHTML = M.ui.error('โหลดการแจ้งเตือนไม่สำเร็จ', err.message); }
  }
  async function aiWorkspace() {
    const access = await gate('ai-workspace', `<div class="mpa-page-head"><div><h1>AI Collaboration Workspace</h1><p>ศูนย์งานร่วมกับ AI สำหรับผู้ดูแลระบบ</p></div></div><section class="mpa-card"><h2 style="margin-top:0">เชื่อมต่อพื้นที่ทำงาน</h2><p class="mpa-muted">หน้านี้สงวนไว้สำหรับข้อมูล AI Workspace เท่านั้น และจะไม่โหลดข้อมูลออร์เดอร์หรือการเงินเพื่อรักษาขอบเขตของแต่ละ MPA route</p><a class="mpa-button" href="../admin.html">เปิด AI Workspace แบบ Compatibility Fallback</a></section>`); if (!access) return;
  }
  async function settings() {
    const access = await gate('settings', `<div class="mpa-page-head"><div><h1>ตั้งค่าธุรกิจกลาง</h1><p>Admin Control Plane: ค่าที่อนุญาตจะบันทึกผ่าน RLS ใน platform_configs</p></div></div><section id="settings" class="mpa-card">${M.ui.loading('กำลังโหลดการตั้งค่ากลาง…')}</section>`); if (!access) return;
    try {
      const rows = await M.request('platform_configs?select=key,value,updated_at&order=key.asc&limit=100', { private: true });
      const byKey = Object.fromEntries((rows || []).map(row => [row.key, row])); const rules = byKey.business_rules?.value || {};
      const numeric = key => rules[key] ?? '';
      $('#settings').innerHTML = `<p class="mpa-muted">เปลี่ยนเฉพาะ key ที่ได้รับอนุมัติเท่านั้น กฎด้านการเงินและความปลอดภัยยังต้องมี Server/RLS เป็นผู้บังคับใช้ ฟอร์มนี้บันทึกค่าไว้เป็นกติกากลาง แต่การเรียกเก็บเงินจริงต้องตรวจฝั่งเซิร์ฟเวอร์เสมอ</p><section class="mpa-card" style="box-shadow:none;border:1px solid var(--ap-line);margin:16px 0"><h2 style="margin-top:0">กติกาค่าส่งและค่าบริการ</h2><p class="mpa-muted">กำหนดค่าเฉพาะเมื่อพร้อมใช้งานจริง ไม่มีการตั้งค่าเริ่มต้นแทนการตัดสินใจของผู้ดูแล</p><form id="businessRules"><div class="mpa-grid" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr))"><div class="mpa-field"><label>ค่าส่งเริ่มต้น (บาท)</label><input data-rule="base_fee" type="number" min="0" step="0.01" value="${h(numeric('base_fee'))}"></div><div class="mpa-field"><label>ระยะทางที่รวมในราคา (กม.)</label><input data-rule="included_km" type="number" min="0" step="0.1" value="${h(numeric('included_km'))}"></div><div class="mpa-field"><label>ค่าส่งต่อกม. (บาท)</label><input data-rule="per_km_fee" type="number" min="0" step="0.01" value="${h(numeric('per_km_fee'))}"></div><div class="mpa-field"><label>ตัวคูณราคาโซน</label><input data-rule="zone_multiplier" type="number" min="0" step="0.1" value="${h(numeric('zone_multiplier'))}"></div><div class="mpa-field"><label>ค่าส่งพัสดุเริ่มต้น (บาท)</label><input data-rule="parcel_base_fee" type="number" min="0" step="0.01" value="${h(numeric('parcel_base_fee'))}"></div><div class="mpa-field"><label>ค่าฝากซื้อเริ่มต้น (บาท)</label><input data-rule="errand_base_fee" type="number" min="0" step="0.01" value="${h(numeric('errand_base_fee'))}"></div><div class="mpa-field"><label>GP ร้านค้า (%)</label><input data-rule="gp_rate_percent" type="number" min="0" max="100" step="0.01" value="${h(numeric('gp_rate_percent'))}"></div><div class="mpa-field"><label>ค่าบริการแพลตฟอร์ม (บาท)</label><input data-rule="service_fee" type="number" min="0" step="0.01" value="${h(numeric('service_fee'))}"></div></div><button class="mpa-button" type="submit">บันทึกกติกากลาง</button></form></section><div class="mpa-table-wrap"><table class="mpa-table"><thead><tr><th>Key</th><th>Value (JSON)</th><th>อัปเดต</th><th></th></tr></thead><tbody>${(rows || []).map(row => `<tr><td><b>${h(row.key)}</b></td><td><textarea data-value="${h(row.key)}" rows="2">${h(JSON.stringify(row.value ?? {}))}</textarea></td><td>${row.updated_at ? new Date(row.updated_at).toLocaleString('th-TH') : '-'}</td><td><button class="mpa-button" data-save="${h(row.key)}">บันทึก</button></td></tr>`).join('') || `<tr><td colspan="4">ยังไม่มี configuration ที่ได้รับอนุมัติให้แก้ไข</td></tr>`}</tbody></table></div>`;
      $('#businessRules').onsubmit = async event => {
        event.preventDefault(); const value = {};
        for (const field of document.querySelectorAll('[data-rule]')) { const raw = field.value.trim(); if (!raw) continue; const number = Number(raw); if (!Number.isFinite(number) || number < 0 || (field.dataset.rule === 'gp_rate_percent' && number > 100)) return M.ui.setNotice('กรุณากรอกค่ากติกาเป็นตัวเลขที่อยู่ในช่วงที่อนุญาต', 'error'); value[field.dataset.rule] = number; }
        if (!Object.keys(value).length) return M.ui.setNotice('กรุณากรอกอย่างน้อยหนึ่งค่าก่อนบันทึก', 'error');
        if (!window.confirm('ยืนยันบันทึกกติกาธุรกิจกลางหรือไม่? ค่านี้ควรถูกบังคับใช้โดยกฎฝั่งเซิร์ฟเวอร์ก่อนใช้กับการเรียกเก็บเงินจริง')) return;
        try { await M.request('platform_configs?on_conflict=key', { method: 'POST', private: true, headers: { Prefer: 'resolution=merge-duplicates,return=minimal' }, body: JSON.stringify({ key: 'business_rules', value, updated_at: M.ui.nowIso() }) }); M.ui.setNotice('บันทึกกติกาธุรกิจกลางแล้ว'); } catch (err) { M.ui.setNotice(err.message, 'error'); }
      };
      document.querySelectorAll('[data-save]').forEach(button => button.onclick = async () => { const key = button.dataset.save, field = document.querySelector(`[data-value="${CSS.escape(key)}"]`); let value; try { value = JSON.parse(field.value); } catch { return M.ui.setNotice('ค่า configuration ต้องอยู่ในรูปแบบ JSON ที่ถูกต้อง', 'error'); } try { await M.request('platform_configs?on_conflict=key', { method: 'POST', private: true, headers: { Prefer: 'resolution=merge-duplicates,return=minimal' }, body: JSON.stringify({ key, value, updated_at: M.ui.nowIso() }) }); M.ui.setNotice('บันทึกการตั้งค่ากลางแล้ว'); } catch (err) { M.ui.setNotice(err.message, 'error'); } });
    } catch (err) { $('#settings').innerHTML = M.ui.error('โหลดการตั้งค่ากลางไม่สำเร็จ', err.message); }
  }
  ({ login, dashboard, orders, stores, promotions, customers, riders, finance, notifications, 'ai-workspace': aiWorkspace, settings }[page] || login)();
})();
