(() => {
  'use strict';
  const boot = () => {
    const R = window.APServiceAdminRuntime;
    if (!R) return setTimeout(boot, 20);
    const { M, $, h, gate } = R;
    const state = { coupons: [], stores: [], menus: [], media: [], couponStores: [], couponMenus: [], editing: null };
    const date = value => value ? new Date(value).toLocaleString('th-TH') : '-';
    const imageUrl = row => row?.visibility === 'public' ? `${M.config.url}/storage/v1/object/public/${encodeURIComponent(row.bucket_id)}/${String(row.storage_path || '').split('/').map(encodeURIComponent).join('/')}?v=${encodeURIComponent(row.version || 1)}` : '';
    const discount = row => row.discount_type === 'percent' ? `${row.discount_value}%` : M.ui.baht(row.discount_value);
    const scope = row => row.scope_type === 'store' ? 'เฉพาะร้านที่เลือก' : row.scope_type === 'menu' ? 'เฉพาะเมนูที่เลือก' : 'ใช้ได้ทุกร้าน';
    const formMarkup = () => `<form id="couponForm" class="coupon-form"><div class="coupon-form-grid"><label class="mpa-field"><span>รหัสคูปอง *</span><input name="code" required maxlength="40" placeholder="WELCOME2026"></label><label class="mpa-field"><span>ชื่อคูปอง *</span><input name="name" required maxlength="120" placeholder="ส่วนลดสมาชิกใหม่"></label><label class="mpa-field full"><span>รายละเอียดคูปอง</span><textarea name="description" rows="2" maxlength="500" placeholder="รายละเอียดและเงื่อนไขที่ลูกค้าควรรู้"></textarea></label><label class="mpa-field"><span>ประเภทส่วนลด *</span><select name="discount_type"><option value="percent">ลดเป็นเปอร์เซ็นต์</option><option value="fixed">ลดเป็นจำนวนเงิน</option></select></label><label class="mpa-field"><span>มูลค่าส่วนลด *</span><input name="discount_value" type="number" min="0.01" step="0.01" required></label><label class="mpa-field"><span>ยอดสั่งซื้อขั้นต่ำ</span><input name="min_order_amount" type="number" min="0" step="0.01" value="0"></label><label class="mpa-field"><span>ขอบเขตการใช้ *</span><select name="scope_type"><option value="all">ทุกสินค้า/ทุกร้าน</option><option value="store">เฉพาะร้าน</option><option value="menu">เฉพาะเมนู</option></select></label><label class="mpa-field"><span>ร้านที่กำหนด</span><select name="store_id"><option value="">เลือกเมื่อใช้เฉพาะร้าน</option>${state.stores.map(row => `<option value="${h(row.id)}">${h(row.name)}</option>`).join('')}</select></label><label class="mpa-field"><span>เมนูที่กำหนด</span><select name="menu_item_id"><option value="">เลือกเมื่อใช้เฉพาะเมนู</option>${state.menus.map(row => `<option value="${h(row.id)}">${h(row.name)} · ${h(row.store_name || 'ไม่ระบุร้าน')}</option>`).join('')}</select></label><label class="mpa-field"><span>จำนวนสิทธิ์รวม</span><input name="max_redemptions" type="number" min="1" placeholder="ไม่จำกัด"></label><label class="mpa-field"><span>จำกัดต่อคน</span><input name="per_customer_limit" type="number" min="1" value="1"></label><label class="mpa-field"><span>เริ่มใช้</span><input name="starts_at" type="datetime-local"></label><label class="mpa-field"><span>หมดอายุ</span><input name="ends_at" type="datetime-local"></label><label class="mpa-field full"><span>รูปภาพคูปองจากคลังสื่อ</span><select name="image_url"><option value="">ไม่ใช้รูปภาพ</option>${state.media.map(row => `<option value="${h(imageUrl(row))}">${h(row.media_type || 'ภาพ')} · ${h(row.storage_path || row.id)}</option>`).join('')}</select><small class="coupon-muted">เลือกจากภาพที่มีสถานะ public/ready ใน Media Registry</small></label></div><div class="coupon-form-actions"><button class="mpa-button" type="submit">${state.editing ? 'บันทึกการแก้ไขคูปอง' : 'สร้างคูปอง'}</button>${state.editing ? '<button class="mpa-button mpa-button-secondary" type="button" data-coupon-cancel>ยกเลิกแก้ไข</button>' : ''}</div></form>`;
    const card = row => `<article class="coupon-card"><div>${row.image_url ? `<img class="coupon-media-preview" src="${h(row.image_url)}" alt="${h(row.name)}">` : '<div class="coupon-media-preview" aria-hidden="true"></div>'}</div><div><h3>${h(row.name)} <span class="mpa-badge">${h(row.code)}</span></h3><p>${h(row.description || 'ไม่มีรายละเอียดเพิ่มเติม')}</p><div class="coupon-card-meta"><span class="mpa-badge">${h(discount(row))}</span><span class="mpa-badge">${h(scope(row))}</span><span class="mpa-badge">${row.active ? 'เปิดใช้งาน' : 'ปิดใช้งาน'}</span></div><p class="coupon-muted">ใช้ได้ ${date(row.starts_at)} ถึง ${row.ends_at ? date(row.ends_at) : 'ไม่มีกำหนด'} · ขั้นต่ำ ${h(M.ui.baht(row.min_order_amount || 0))}</p></div><div class="coupon-card-actions"><button class="mpa-button mpa-button-secondary" type="button" data-coupon-edit="${h(row.id)}">แก้ไข</button><button class="mpa-button mpa-button-secondary" type="button" data-coupon-toggle="${h(row.id)}">${row.active ? 'ปิดใช้งาน' : 'เปิดใช้งาน'}</button><button class="mpa-button mpa-button-secondary" type="button" data-coupon-delete="${h(row.id)}">ลบ</button></div></article>`;
    const render = () => { const host = $('#coupons'); if (!host) return; host.innerHTML = `<div class="mpa-page-head"><div><span class="admin-kicker">COUPONS</span><h1>จัดการคูปอง</h1><p>สร้างคูปองส่วนลดสำหรับลูกค้า พร้อมกำหนดร้าน เมนู ช่วงเวลา และจำนวนสิทธิ์</p></div><a class="mpa-button mpa-button-secondary" href="dashboard.html">กลับภาพรวม</a></div><section class="mpa-card"><h2>${state.editing ? 'แก้ไขคูปอง' : 'สร้างคูปองใหม่'}</h2>${formMarkup()}</section><section class="mpa-card" style="margin-top:16px"><div class="mpa-page-head"><div><h2>คูปองทั้งหมด</h2><p>รายการนี้เป็นข้อมูลที่ Admin สร้างและลูกค้าจะเห็นตามสถานะ/ช่วงเวลา</p></div><strong>${state.coupons.length} รายการ</strong></div><div class="coupon-list">${state.coupons.map(card).join('') || '<p class="coupon-muted">ยังไม่มีคูปอง กรุณาสร้างรายการแรก</p>'}</div></section>`; bind(); };
    const bind = () => { const form = $('#couponForm'); if (!form) return; form.scope_type.onchange = () => { form.store_id.disabled = form.scope_type.value !== 'store'; form.menu_item_id.disabled = form.scope_type.value !== 'menu'; }; form.scope_type.onchange(); if (state.editing) { const row = state.coupons.find(item => item.id === state.editing); if (row) Object.entries({ code: row.code, name: row.name, description: row.description, discount_type: row.discount_type, discount_value: row.discount_value, min_order_amount: row.min_order_amount, scope_type: row.scope_type, store_id: state.couponStores.find(item => item.coupon_id === row.id)?.store_id || '', menu_item_id: state.couponMenus.find(item => item.coupon_id === row.id)?.menu_item_id || '', max_redemptions: row.max_redemptions || '', per_customer_limit: row.per_customer_limit, image_url: row.image_url || '' }).forEach(([key, value]) => { if (form[key]) form[key].value = value; }); }
      form.onsubmit = async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form).entries()); const value = { code: data.code.trim().toUpperCase(), name: data.name.trim(), description: data.description.trim(), image_url: data.image_url || null, discount_type: data.discount_type, discount_value: Number(data.discount_value), scope_type: data.scope_type, min_order_amount: Number(data.min_order_amount || 0), starts_at: data.starts_at ? new Date(data.starts_at).toISOString() : new Date().toISOString(), ends_at: data.ends_at ? new Date(data.ends_at).toISOString() : null, max_redemptions: data.max_redemptions ? Number(data.max_redemptions) : null, per_customer_limit: Number(data.per_customer_limit || 1), active: true }; if (!value.code || !value.name || !Number.isFinite(value.discount_value) || value.discount_value <= 0) return M.ui.setNotice('กรุณากรอกรหัส ชื่อ และมูลค่าส่วนลดให้ถูกต้อง', 'error'); if (value.discount_type === 'percent' && value.discount_value > 100) return M.ui.setNotice('ส่วนลดเปอร์เซ็นต์ต้องไม่เกิน 100%', 'error'); if (value.scope_type === 'store' && !data.store_id) return M.ui.setNotice('กรุณาเลือกร้านที่ใช้คูปอง', 'error'); if (value.scope_type === 'menu' && !data.menu_item_id) return M.ui.setNotice('กรุณาเลือกเมนูที่ใช้คูปอง', 'error'); try { let row; if (state.editing) { const updated = await M.request(`coupons?id=eq.${encodeURIComponent(state.editing)}`, { method: 'PATCH', private: true, headers: { Prefer: 'return=representation' }, body: JSON.stringify(value) }); row = updated?.[0]; await M.request(`coupon_stores?coupon_id=eq.${encodeURIComponent(state.editing)}`, { method: 'DELETE', private: true }); await M.request(`coupon_menu_items?coupon_id=eq.${encodeURIComponent(state.editing)}`, { method: 'DELETE', private: true }); } else { const created = await M.request('coupons', { method: 'POST', private: true, headers: { Prefer: 'return=representation' }, body: JSON.stringify(value) }); row = created?.[0]; } if (!row?.id) throw new Error('ระบบไม่ส่งข้อมูลคูปองกลับมา'); if (value.scope_type === 'store') await M.request('coupon_stores', { method: 'POST', private: true, body: JSON.stringify({ coupon_id: row.id, store_id: data.store_id }) }); if (value.scope_type === 'menu') await M.request('coupon_menu_items', { method: 'POST', private: true, body: JSON.stringify({ coupon_id: row.id, menu_item_id: data.menu_item_id }) }); M.ui.setNotice(state.editing ? 'แก้ไขคูปองแล้ว' : 'สร้างคูปองแล้ว'); state.editing = null; await load(); } catch (error) { M.ui.setNotice(error.message || 'บันทึกคูปองไม่สำเร็จ', 'error'); } };
      form.querySelector('[data-coupon-cancel]')?.addEventListener('click', () => { state.editing = null; render(); });
      document.querySelectorAll('[data-coupon-edit]').forEach(button => button.onclick = () => { state.editing = button.dataset.couponEdit; render(); });
      document.querySelectorAll('[data-coupon-toggle]').forEach(button => button.onclick = async () => { const row = state.coupons.find(item => item.id === button.dataset.couponToggle); if (!row) return; try { await M.request(`coupons?id=eq.${encodeURIComponent(row.id)}`, { method: 'PATCH', private: true, body: JSON.stringify({ active: !row.active, updated_at: new Date().toISOString() }) }); M.ui.setNotice(row.active ? 'ปิดใช้งานคูปองแล้ว' : 'เปิดใช้งานคูปองแล้ว'); await load(); } catch (error) { M.ui.setNotice(error.message || 'เปลี่ยนสถานะคูปองไม่สำเร็จ', 'error'); } });
      document.querySelectorAll('[data-coupon-delete]').forEach(button => button.onclick = async () => { const row = state.coupons.find(item => item.id === button.dataset.couponDelete); if (!row || !window.confirm(`ยืนยันลบคูปอง ${row.name} หรือไม่?`)) return; try { await M.request(`coupons?id=eq.${encodeURIComponent(row.id)}`, { method: 'DELETE', private: true }); M.ui.setNotice('ลบคูปองแล้ว'); await load(); } catch (error) { M.ui.setNotice(error.message || 'ลบคูปองไม่สำเร็จ', 'error'); } });
    };
    async function load() { try { const [coupons, stores, menus, media, couponStores, couponMenus] = await Promise.all([M.request('coupons?select=*&order=created_at.desc&limit=200', { private: true, forceFresh: true }), M.request('stores?select=id,name&order=name.asc&limit=500', { private: true, cacheTtlMs: 30_000 }), M.request('menu_items?select=id,name,store_id&order=name.asc&limit=1000', { private: true, cacheTtlMs: 30_000 }), M.request('media_assets?select=id,bucket_id,storage_path,version,visibility,media_type,status&visibility=eq.public&status=eq.ready&order=created_at.desc&limit=200', { private: true, cacheTtlMs: 30_000 }), M.request('coupon_stores?select=coupon_id,store_id&limit=1000', { private: true, cacheTtlMs: 30_000 }), M.request('coupon_menu_items?select=coupon_id,menu_item_id&limit=1000', { private: true, cacheTtlMs: 30_000 })]); state.coupons = coupons || []; state.couponStores = couponStores || []; state.couponMenus = couponMenus || []; state.stores = stores || []; state.media = media || []; state.menus = (menus || []).map(row => ({ ...row, store_name: state.stores.find(store => store.id === row.store_id)?.name || '' })); render(); } catch (error) { const host = $('#coupons'); if (host) host.innerHTML = M.ui.error('โหลดระบบคูปองไม่สำเร็จ', error.message); } }
    gate('admin', '<div id="coupons">กำลังโหลดระบบคูปอง…</div>').then(access => { if (access !== false) load(); });
  };
  window.APServiceAdminCoupons = { mount: boot };
})();
