/* Admin Login Media management — additive. */
(function () {
  'use strict';
  const URL = 'https://abtsctwfkgzciseppach.supabase.co';
  const KEY = 'sb_publishable_TyJWnKkbS8vKcQKKAzoqSg_BOguwKRv';
  const sessionKey = 'apservice_mpa_session_v1';
  const $ = (id) => document.getElementById(id);
  const message = (text, error = false) => { $('login-media-message').textContent = text; $('login-media-message').style.color = error ? '#b63b4b' : '#176b87'; };
  function token() { try { return JSON.parse(localStorage.getItem(sessionKey) || 'null')?.access_token || ''; } catch { return ''; } }
  async function api(path, options = {}) { const access = token(); if (!access) throw new Error('กรุณาเข้าสู่ระบบด้วยบัญชี Admin'); const response = await fetch(`${URL}/rest/v1/${path}`, { ...options, headers: { apikey: KEY, Authorization: `Bearer ${access}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.message || body?.msg || body?.hint || 'ไม่สามารถเชื่อมต่อข้อมูลได้'); return body; }
  async function compressImage(file) {
    if (file.type === 'image/gif') return { file, kind: 'animated_gif' };
    const bitmap = await createImageBitmap(file); const scale = Math.min(1, 1200 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(bitmap.width * scale)); canvas.height = Math.max(1, Math.round(bitmap.height * scale)); canvas.getContext('2d').drawImage(bitmap, 0, 0, canvas.width, canvas.height); const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.82)); if (!blob) throw new Error('ไม่สามารถบีบอัดรูปภาพได้'); return { file: new File([blob], `${file.name.replace(/\.[^.]+$/, '')}.jpg`, { type: 'image/jpeg' }), kind: 'static_image' };
  }
  async function upload(file) { const result = await compressImage(file); const path = `login-media/${crypto.randomUUID()}${result.kind === 'animated_gif' ? '.gif' : '.jpg'}`; const access = token(); const response = await fetch(`${URL}/storage/v1/object/catalog/${path}`, { method: 'POST', headers: { apikey: KEY, Authorization: `Bearer ${access}`, 'x-upsert': 'false', 'Content-Type': result.file.type }, body: result.file }); if (!response.ok) throw new Error('อัปโหลดไฟล์ไม่สำเร็จ'); return { path, url: `${URL}/storage/v1/object/public/catalog/${path}`, kind: result.kind }; }
  function iso(id) { const value = $(id).value; return value ? new Date(value).toISOString() : null; }
  let loginMediaPreviewUrl = ''; const loginMediaPreview = document.createElement('figure'); loginMediaPreview.hidden = true; loginMediaPreview.style.cssText = 'margin:12px 0;padding:10px;border:1px solid #dce5ea;border-radius:12px'; loginMediaPreview.innerHTML = '<img alt="ตัวอย่างสื่อ Login ที่เลือก" style="display:block;max-width:100%;max-height:220px;border-radius:8px;object-fit:contain"><figcaption class="muted"></figcaption>'; $('login-media-file').insertAdjacentElement('afterend', loginMediaPreview); const clearLoginMediaPreview = () => { if (loginMediaPreviewUrl) { URL.revokeObjectURL(loginMediaPreviewUrl); loginMediaPreviewUrl = ''; } loginMediaPreview.hidden = true; loginMediaPreview.querySelector('img').removeAttribute('src'); loginMediaPreview.querySelector('figcaption').textContent = ''; }; $('login-media-file').addEventListener('change', event => { clearLoginMediaPreview(); const file = event.target.files?.[0]; if (!file) return; loginMediaPreviewUrl = URL.createObjectURL(file); loginMediaPreview.hidden = false; loginMediaPreview.querySelector('img').src = loginMediaPreviewUrl; loginMediaPreview.querySelector('figcaption').textContent = `${file.name} · ${Math.ceil(file.size / 1024)} KB · ตัวอย่างก่อนบันทึก`; }); addEventListener('pagehide', clearLoginMediaPreview, { once: true }); async function save(event) { event.preventDefault(); const button = event.currentTarget.querySelector('button[type="submit"]'); const file = $('login-media-file').files[0]; if (!file) return; button.disabled = true; message('กำลังบีบอัดและอัปโหลด…'); try { const uploaded = await upload(file); await api('rpc/admin_upsert_login_background_media', { method: 'POST', body: JSON.stringify({ p_title: $('login-media-title').value.trim(), p_target_app: $('login-media-target').value, p_media_kind: uploaded.kind, p_storage_path: uploaded.path, p_public_url: uploaded.url, p_festival_key: $('login-media-festival').value.trim() || null, p_starts_at: iso('login-media-start'), p_ends_at: iso('login-media-end'), p_priority: Number($('login-media-priority').value || 0), p_overlay_opacity: Number($('login-media-opacity').value || 0.18), p_is_active: true }) }); event.currentTarget.reset(); $('login-media-opacity').value = '0.18'; clearLoginMediaPreview(); message('บันทึกสื่อ Login สำเร็จ'); await load(); } catch (error) { message(error.message || 'ไม่สามารถบันทึกสื่อได้', true); } finally { button.disabled = false; } }
  async function disable(id) { if (!window.confirm('ปิดใช้งานสื่อนี้หรือไม่')) return; try { await api('rpc/admin_disable_login_background_media', { method: 'POST', body: JSON.stringify({ p_id: id }) }); await load(); } catch (error) { message(error.message || 'ไม่สามารถปิดใช้งานได้', true); } }
  async function load() { const host = $('login-media-list'); host.innerHTML = '<p class="hint">กำลังโหลด…</p>'; try { const rows = await api('rpc/admin_list_login_background_media', { method: 'POST', body: '{}' }); host.innerHTML = Array.isArray(rows) && rows.length ? rows.map((row) => `<article class="media-row"><img class="thumb" src="${row.public_url}" alt=""><div><strong>${escapeHtml(row.title)}</strong><div class="muted">${escapeHtml(row.target_app)} · ${escapeHtml(row.media_kind)} · priority ${row.priority}</div><div class="muted">${row.starts_at ? new Date(row.starts_at).toLocaleString('th-TH') : 'ทันที'} – ${row.ends_at ? new Date(row.ends_at).toLocaleString('th-TH') : 'ไม่หมดอายุ'} · ${row.is_active ? 'กำลังใช้งาน' : 'ปิดใช้งาน'}</div></div><div class="row"><button class="button danger" type="button" data-disable="${row.id}" ${row.is_active ? '' : 'disabled'}>ปิดใช้งาน</button></div></article>`).join('') : '<p class="hint">ยังไม่มีสื่อ Login</p>'; } catch (error) { host.innerHTML = `<p class="hint">${escapeHtml(error.message || 'โหลดข้อมูลไม่สำเร็จ')}</p>`; } }
  function escapeHtml(value) { return String(value || '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
  $('login-media-form').addEventListener('submit', save); $('login-media-refresh').addEventListener('click', load); $('login-media-list').addEventListener('click', (event) => { const id = event.target.closest('[data-disable]')?.dataset.disable; if (id) disable(id); }); load();
})();
